# Generated by Django 4.2.5 on 2023-09-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bouquet_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BouquetType',
            fields=[
                ('bouquet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('image_url', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bouquet_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'managers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'service_request',
                'managed': False,
            },
        ),
    ]
