# Generated by Django 4.2.5 on 2023-12-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetApplication',
            fields=[
                ('bouquet_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'bouquet_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=30, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_address', models.CharField(blank=True, max_length=100, null=True)),
                ('receiving_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'service_application',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BouquetRequest',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
