# Generated by Django 4.2.5 on 2023-12-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bouquetapplication_serviceapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
